from pathlib import Path
p=Path('app-runtime.js')
s=p.read_text()
old="async function getMicStream(){const tracks=micStream?.getAudioTracks?.()||[];const reusable=micStream&&micStream.active&&tracks.some(t=>t.readyState==='live'&&t.enabled&&!t.muted);if(reusable)return micStream;if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null}note('microphone',{phase:'permission_request'});micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});const track=micStream.getAudioTracks()[0];if(!track||track.readyState!=='live'||!track.enabled){releaseMicrophone();throw Object.assign(new Error('Safari did not provide a usable microphone stream.'),{name:'NotReadableError'})}localStorage.setItem('bolna_mic_setup_done','1');micSetup=false;note('microphone',{phase:'ready',muted:!!track.muted,enabled:!!track.enabled});return micStream}"
new="async function waitForMicTrack(track,ms=350){if(!track||track.readyState!=='live'||!track.enabled)return false;if(!track.muted)return true;await Promise.race([new Promise(resolve=>track.addEventListener('unmute',resolve,{once:true})),new Promise(resolve=>setTimeout(resolve,ms))]);return track.readyState==='live'&&track.enabled&&!track.muted}\nasync function getMicStream(){const current=micStream?.getAudioTracks?.()[0];if(micStream&&micStream.active&&await waitForMicTrack(current,300))return micStream;if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null}note('microphone',{phase:'permission_request'});micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});const track=micStream.getAudioTracks()[0];if(!await waitForMicTrack(track,500)){releaseMicrophone();throw Object.assign(new Error('Safari did not provide a usable microphone stream.'),{name:'NotReadableError'})}localStorage.setItem('bolna_mic_setup_done','1');micSetup=false;note('microphone',{phase:'ready',muted:!!track.muted,enabled:!!track.enabled});return micStream}"
if old not in s: raise SystemExit('reviewed getMicStream anchor not found')
s=s.replace(old,new,1)
old="const stream=await getMicStream();const track=stream.getAudioTracks()[0];if(track?.muted)await Promise.race([new Promise(resolve=>track.addEventListener('unmute',resolve,{once:true})),new Promise(resolve=>setTimeout(resolve,450))]);const mime=pickMime();recorder="
new="const stream=await getMicStream();const mime=pickMime();recorder="
if old not in s: raise SystemExit('reviewed startListening anchor not found')
s=s.replace(old,new,1)
p.write_text(s)
