from pathlib import Path
import re

# Backend: add voiceCore multimodal operation
p=Path('api/gemini.js')
s=p.read_text()
s=s.replace("if (!['transcribe', 'generate', 'enrich', 'tts'].includes(body.operation)) return 'Unsupported operation.';", "if (!['transcribe', 'voiceCore', 'generate', 'enrich', 'tts'].includes(body.operation)) return 'Unsupported operation.';")
s=s.replace("  if (body.operation === 'transcribe') {\n    if (typeof body.audioData !== 'string' || !body.audioData) return 'audioData is required.';\n    if (body.audioMime !== 'audio/wav') return 'Bolna transcription requires normalized audio/wav.';\n    if (body.audioData.length > LIMITS.audioBase64Chars) return 'Recording is too large.';\n  }", "  if (body.operation === 'transcribe' || body.operation === 'voiceCore') {\n    if (typeof body.audioData !== 'string' || !body.audioData) return 'audioData is required.';\n    if (body.audioMime !== 'audio/wav') return 'Bolna voice processing requires normalized audio/wav.';\n    if (body.audioData.length > LIMITS.audioBase64Chars) return 'Recording is too large.';\n  }\n\n  if (body.operation === 'voiceCore') {\n    if (typeof body.prompt !== 'string' || !body.prompt.trim()) return 'prompt is required.';\n    if (body.prompt.length > LIMITS.promptChars) return 'Prompt is too large.';\n    if (!body.schema || JSON.stringify(body.schema).length > LIMITS.schemaChars) return 'A valid schema is required.';\n  }")
anchor="function providerRequest(body) {\n  if (body.operation === 'transcribe') {"
insert="function providerRequest(body) {\n  if (body.operation === 'voiceCore') {\n    return {\n      timeoutMs: 8500,\n      retryTimeoutMs: 8500,\n      request: {\n        model: MODELS.generate,\n        input: [\n          { type: 'text', text: body.prompt },\n          { type: 'audio', data: body.audioData, mime_type: 'audio/wav' },\n        ],\n        generation_config: { thinking_level: 'minimal' },\n        response_format: { type: 'text', mime_type: 'application/json', schema: body.schema },\n      },\n    };\n  }\n  if (body.operation === 'transcribe') {"
if anchor not in s: raise SystemExit('backend provider anchor not found')
s=s.replace(anchor,insert)
s=s.replace("mimeType: req.body.operation === 'transcribe' ? 'audio/wav' : undefined,\n    recordingBytesApprox: req.body.operation === 'transcribe' ? Math.floor(req.body.audioData.length * 0.75) : undefined,", "mimeType: ['transcribe','voiceCore'].includes(req.body.operation) ? 'audio/wav' : undefined,\n    recordingBytesApprox: ['transcribe','voiceCore'].includes(req.body.operation) ? Math.floor(req.body.audioData.length * 0.75) : undefined,")
p.write_text(s)

# Frontend: single-pass voice result + independent audio preparation state
p=Path('app-runtime.js')
s=p.read_text()
core="const coreSchema={type:'object',properties:{natural:{type:'string'},spokenForm:{type:'string'},phonetic:{type:'string'},meaning:{type:'string'},speechText:{type:'string'},confidence:{type:'number'},phoneticConfidence:{type:'string',enum:['high','medium']}},required:['natural','spokenForm','phonetic','meaning','speechText','confidence','phoneticConfidence'],additionalProperties:false};"
if core not in s: raise SystemExit('core schema anchor not found')
s=s.replace(core, core+"\nconst voiceCoreSchema={type:'object',properties:{transcript:{type:'string'},natural:{type:'string'},spokenForm:{type:'string'},phonetic:{type:'string'},meaning:{type:'string'},speechText:{type:'string'},confidence:{type:'number'},phoneticConfidence:{type:'string',enum:['high','medium']}},required:['transcript','natural','spokenForm','phonetic','meaning','speechText','confidence','phoneticConfidence'],additionalProperties:false};")
s=s.replace("let view='speak',state='idle',transcript='',result=null,error=null,showType=false,panel='';", "let view='speak',state='idle',transcript='',result=null,error=null,showType=false,panel='',audioStatus='idle';")
needle="function corePrompt(english){return `You are Bolna's expert contemporary Hinglish speaker and Hindi pronunciation coach for American English speakers."
idx=s.index(needle)
voice_fn="function voiceCorePrompt(){return `You are Bolna's expert contemporary Hinglish speaker, Hindi pronunciation coach, and English speech transcriber for American English speakers.\nListen to the short English utterance. First transcribe it exactly with normal punctuation. Then produce the natural contemporary Hinglish the user should say in the current context.\nContext: ${JSON.stringify(context)}\nReturn exactly: transcript, natural, spokenForm, phonetic, meaning, speechText, confidence, phoneticConfidence.\nThe phonetic field is critical and must follow this standard:\n${pronunciationRules}\nDo not wait for, discuss, or generate audio. Return only the requested JSON.`}\nasync function generateVoiceCore(blob){const t0=performance.now();const normalized=await normalizeRecording(blob);note('normalize',{ms:Math.round(performance.now()-t0),sourceMime:blob.type||'unknown',normalizedBytes:normalized.size});const x=await provider('voiceCore',{audioData:await blob64(normalized),audioMime:'audio/wav',prompt:voiceCorePrompt(),schema:voiceCoreSchema},19000);const t=outText(x);if(!t)throw Object.assign(new Error('Gemini returned no voice result.'),{userTitle:'Empty Gemini result'});try{return JSON.parse(t)}catch{throw Object.assign(new Error('Gemini returned malformed voice data.'),{userTitle:'Invalid Gemini result'})}}\n"
s=s[:idx]+voice_fn+s[idx:]
s=s.replace("function prefetchVoice(text){if(text)void speech(text,false).catch(()=>{})}", "function prefetchVoice(text){if(!text)return;audioStatus='preparing';render();void speech(text,false).then(()=>{audioStatus='ready';if(result)render()}).catch(e=>{audioStatus=e?.category==='quota_exhausted'?'unavailable':'error';if(result)render()})}")
s=s.replace("<button class=\"hear\" id=\"hear\">${state==='playing'?'Playing…':'▶  Hear it'}</button>", "<button class=\"hear\" id=\"hear\" ${audioStatus==='preparing'?'disabled':''}>${state==='playing'?'Playing…':audioStatus==='preparing'?'Preparing audio…':audioStatus==='unavailable'?'Audio unavailable':'▶  Hear it'}</button>")
s=s.replace("document.getElementById('again').onclick=()=>{result=null;transcript='';state='idle';panel='';render()}", "document.getElementById('again').onclick=()=>{result=null;transcript='';state='idle';panel='';audioStatus='idle';render()}")
pattern=re.compile(r"state='transcribing';render\(\);transcript=await transcribe\(b\);.*?prefetchVoice\(result\.speechText\)", re.S)
replacement="state='generating';render();const d=await generateVoiceCore(b);if(id!==reqId)return;transcript=(d.transcript||'').trim();if(!transcript)throw Object.assign(new Error('No speech was returned from the recording.'),{userTitle:'I didn’t hear that clearly'});localStorage.setItem('bolna_voice_used','1');const inferred=infer(transcript);if(context==='General'&&inferred){context=inferred;localStorage.setItem('bolna_context',inferred)}const {transcript:_spokenTranscript,...core}=d;result={...core,polite:'',casual:'',moreHindi:'',words:[],_enriched:false};state='ready';audioStatus='idle';remember();render();prefetchVoice(result.speechText)"
s,n=pattern.subn(replacement,s,count=1)
if n!=1: raise SystemExit(f'voice path replacements={n}')
p.write_text(s)
