window.BOLNA_LIBRARY = [
  // Getting around
  {category:'Getting around',context:'Driver',english:'Please stop here.',natural:'Bhaiya, yahin rok dena.',phonetic:'BHAI-yaa, ya-HEE(n) rohk DAY-naa.'},
  {category:'Getting around',context:'Driver',english:'Please go a little further.',natural:'Thoda aur aage chaliye.',phonetic:'THOH-daa aur AA-gay chuh-LEE-yay.'},
  {category:'Getting around',context:'Driver',english:'Take the next left.',natural:'Agla left le lijiye.',phonetic:'UG-laa left lay LEE-jee-yay.'},
  {category:'Getting around',context:'Driver',english:'Take the next right.',natural:'Agla right le lijiye.',phonetic:'UG-laa right lay LEE-jee-yay.'},
  {category:'Getting around',context:'Driver',english:'Please follow Google Maps.',natural:'Google Maps follow kar lijiye.',phonetic:'Google Maps FAH-loh kur LEE-jee-yay.'},
  {category:'Getting around',context:'Driver',english:'Can you wait here for five minutes?',natural:'Paanch minute yahin wait kar sakte hain?',phonetic:'PAA(n)ch MIN-it ya-HEE(n) wait kur SUK-tay hai(n)?'},
  {category:'Getting around',context:'Driver',english:'How long will it take?',natural:'Kitna time lagega?',phonetic:'KIT-naa time LUG-ay-gaa?'},
  {category:'Getting around',context:'Driver',english:'Is there a lot of traffic?',natural:'Traffic zyada hai kya?',phonetic:'Traffic ZYAA-daa hai kyaa?'},
  {category:'Getting around',context:'Driver',english:'Please take the faster route.',natural:'Fast wala route le lijiye.',phonetic:'Fast WAA-laa route lay LEE-jee-yay.'},
  {category:'Getting around',context:'Driver',english:'I will get out here.',natural:'Main yahin utar jaaunga.',phonetic:'May(n) ya-HEE(n) OO-tur JAA-oon-gaa.'},

  // Taxi / auto
  {category:'Taxi & auto',context:'Driver',english:'Will you go to this location?',natural:'Is location pe chalenge?',phonetic:'Iss loh-KAY-shun pay chuh-LAY(n)-gay?'},
  {category:'Taxi & auto',context:'Driver',english:'Please turn the AC down a little.',natural:'AC thoda kam kar dijiye.',phonetic:'A-C THOH-daa kum kur DEE-jee-yay.'},
  {category:'Taxi & auto',context:'Driver',english:'Please turn the AC up a little.',natural:'AC thoda badha dijiye.',phonetic:'A-C THOH-daa buh-DHAA DEE-jee-yay.'},
  {category:'Taxi & auto',context:'Driver',english:'Please drive a little slower.',natural:'Thoda dheere chalaaiye.',phonetic:'THOH-daa DHEE-ray chuh-LAA-ee-yay.'},
  {category:'Taxi & auto',context:'Driver',english:'Please drive a little faster.',natural:'Thoda jaldi chalaaiye.',phonetic:'THOH-daa JUL-dee chuh-LAA-ee-yay.'},
  {category:'Taxi & auto',context:'Driver',english:'Please drop me at the main gate.',natural:'Main gate pe drop kar dijiye.',phonetic:'Main gate pay drop kur DEE-jee-yay.'},
  {category:'Taxi & auto',context:'Driver',english:'Please call me when you arrive.',natural:'Pahunch ke call kar dena.',phonetic:'puh-HOONCH kay call kur DAY-naa.'},
  {category:'Taxi & auto',context:'Driver',english:'I am coming downstairs.',natural:'Main neeche aa raha hoon.',phonetic:'May(n) NEE-chay aa RUH-haa hoo(n).'},
  {category:'Taxi & auto',context:'Driver',english:'I will be there in two minutes.',natural:'Main do minute mein aa raha hoon.',phonetic:'May(n) doh MIN-it may(n) aa RUH-haa hoo(n).'},
  {category:'Taxi & auto',context:'Driver',english:'Please do not cancel the ride.',natural:'Ride cancel mat karna, please.',phonetic:'Ride CAN-sul mut KUR-naa, please.'},

  // Home
  {category:'At home',context:'Household',english:'Please leave this here.',natural:'Ye yahin rakh dijiye.',phonetic:'Yay ya-HEE(n) rukh DEE-jee-yay.'},
  {category:'At home',context:'Household',english:'Please put this in the kitchen.',natural:'Ye kitchen mein rakh dijiye.',phonetic:'Yay kitchen may(n) rukh DEE-jee-yay.'},
  {category:'At home',context:'Household',english:'Please close the door.',natural:'Darwaza band kar dijiye.',phonetic:'dur-WAA-zaa bund kur DEE-jee-yay.'},
  {category:'At home',context:'Household',english:'Please open the window.',natural:'Khidki khol dijiye.',phonetic:'KHID-kee khohl DEE-jee-yay.'},
  {category:'At home',context:'Household',english:'Can you come tomorrow morning?',natural:'Kal subah aa sakte hain?',phonetic:'Kul SOO-buh aa SUK-tay hai(n)?'},
  {category:'At home',context:'Household',english:'Please come a little earlier tomorrow.',natural:'Kal thoda jaldi aa jaiye.',phonetic:'Kul THOH-daa JUL-dee aa JAA-ee-yay.'},
  {category:'At home',context:'Household',english:'Please clean this room first.',natural:'Pehle ye room saaf kar dijiye.',phonetic:'PAY-lay yay room saaf kur DEE-jee-yay.'},
  {category:'At home',context:'Household',english:'Please do not throw this away.',natural:'Ye mat phenkiye.',phonetic:'Yay mut FAY(n)-kee-yay.'},
  {category:'At home',context:'Household',english:'Please keep this separately.',natural:'Isko alag rakh dijiye.',phonetic:'ISS-koh uh-LUG rukh DEE-jee-yay.'},
  {category:'At home',context:'Household',english:'That is enough for today.',natural:'Aaj ke liye itna kaafi hai.',phonetic:'Aaj kay LEE-yay IT-naa KAA-fee hai.'},

  // Apartment / maintenance
  {category:'Apartment & maintenance',context:'Professional',english:'The AC is not working.',natural:'AC kaam nahi kar raha hai.',phonetic:'A-C kaam nuh-HEE(n) kur RUH-haa hai.'},
  {category:'Apartment & maintenance',context:'Professional',english:'There is no hot water.',natural:'Garam paani nahi aa raha hai.',phonetic:'GUH-rum PAA-nee nuh-HEE(n) aa RUH-haa hai.'},
  {category:'Apartment & maintenance',context:'Professional',english:'The internet is not working.',natural:'Internet nahi chal raha hai.',phonetic:'Internet nuh-HEE(n) chul RUH-haa hai.'},
  {category:'Apartment & maintenance',context:'Professional',english:'There is a leak in the bathroom.',natural:'Bathroom mein leak ho raha hai.',phonetic:'Bathroom may(n) leak hoh RUH-haa hai.'},
  {category:'Apartment & maintenance',context:'Professional',english:'When can someone come to fix it?',natural:'Isko theek karne koi kab aa sakta hai?',phonetic:'ISS-koh theek KUR-nay koyee kub aa SUK-taa hai?'},
  {category:'Apartment & maintenance',context:'Professional',english:'Please send someone today.',natural:'Aaj kisi ko bhej dijiye.',phonetic:'Aaj KISS-ee koh bhayj DEE-jee-yay.'},
  {category:'Apartment & maintenance',context:'Professional',english:'Please call before coming.',natural:'Aane se pehle call karna.',phonetic:'AA-nay say PAY-lay call KUR-naa.'},
  {category:'Apartment & maintenance',context:'Professional',english:'How much will the repair cost?',natural:'Repair ka kitna kharcha hoga?',phonetic:'Repair kaa KIT-naa KHUR-chaa HOH-gaa?'},
  {category:'Apartment & maintenance',context:'Professional',english:'Please check this again.',natural:'Ek baar phir check kar lijiye.',phonetic:'Ayk baar fir check kur LEE-jee-yay.'},
  {category:'Apartment & maintenance',context:'Professional',english:'It is working now, thank you.',natural:'Ab theek chal raha hai, thank you.',phonetic:'Ub theek chul RUH-haa hai, thank you.'},

  // Security & delivery
  {category:'Security & delivery',context:'Security',english:'Please let the delivery person in.',natural:'Delivery wale ko andar aane dijiye.',phonetic:'Delivery WAA-lay koh UN-dur AA-nay DEE-jee-yay.'},
  {category:'Security & delivery',context:'Security',english:'Please send them upstairs.',natural:'Unko upar bhej dijiye.',phonetic:'OON-koh OO-pur bhayj DEE-jee-yay.'},
  {category:'Security & delivery',context:'Security',english:'I am expecting a guest.',natural:'Mera guest aane wala hai.',phonetic:'MAY-raa guest AA-nay WAA-laa hai.'},
  {category:'Security & delivery',context:'Security',english:'Please call me when they arrive.',natural:'Woh aayein toh mujhe call kar dijiye.',phonetic:'Voh AA-yay(n) toh MOO-jhay call kur DEE-jee-yay.'},
  {category:'Security & delivery',context:'Delivery',english:'Please leave it at the door.',natural:'Door ke paas chhod dena.',phonetic:'Door kay paas chhohd DAY-naa.'},
  {category:'Security & delivery',context:'Delivery',english:'Please leave it at the gate.',natural:'Gate pe chhod dena.',phonetic:'Gate pay chhohd DAY-naa.'},
  {category:'Security & delivery',context:'Delivery',english:'Please wait two minutes.',natural:'Do minute wait karna, please.',phonetic:'Doh MIN-it wait KUR-naa, please.'},
  {category:'Security & delivery',context:'Delivery',english:'Please send me your location.',natural:'Apni location bhej dena.',phonetic:'UP-nee loh-KAY-shun bhayj DAY-naa.'},
  {category:'Security & delivery',context:'Delivery',english:'I cannot find you.',natural:'Mujhe aap nahi dikh rahe.',phonetic:'MOO-jhay aap nuh-HEE(n) dikh RUH-hay.'},
  {category:'Security & delivery',context:'Delivery',english:'I am coming to the gate.',natural:'Main gate pe aa raha hoon.',phonetic:'May(n) gate pay aa RUH-haa hoo(n).'},

  // Restaurants
  {category:'Restaurants',context:'Restaurant',english:'Can I get the bill?',natural:'Bill mil jayega?',phonetic:'Bill mil JAA-yay-gaa?'},
  {category:'Restaurants',context:'Restaurant',english:'Please make it a little less spicy.',natural:'Thoda kam spicy karna, please.',phonetic:'THOH-daa kum spicy KUR-naa, please.'},
  {category:'Restaurants',context:'Restaurant',english:'Please make it without chili.',natural:'Mirchi ke bina bana dijiye.',phonetic:'MIR-chee kay BEE-naa buh-NAA DEE-jee-yay.'},
  {category:'Restaurants',context:'Restaurant',english:'Can you pack this to go?',natural:'Isko pack kar dijiye.',phonetic:'ISS-koh pack kur DEE-jee-yay.'},
  {category:'Restaurants',context:'Restaurant',english:'Do you have bottled water?',natural:'Bottled water hai?',phonetic:'Bottled water hai?'},
  {category:'Restaurants',context:'Restaurant',english:'Can we get a table for two?',natural:'Do logon ke liye table mil jayega?',phonetic:'Doh LOH-goh(n) kay LEE-yay table mil JAA-yay-gaa?'},
  {category:'Restaurants',context:'Restaurant',english:'What do you recommend?',natural:'Aap kya recommend karenge?',phonetic:'Aap kyaa recommend kuh-RAY(n)-gay?'},
  {category:'Restaurants',context:'Restaurant',english:'Is this vegetarian?',natural:'Ye veg hai?',phonetic:'Yay veg hai?'},
  {category:'Restaurants',context:'Restaurant',english:'Does this have nuts?',natural:'Ismein nuts hain?',phonetic:'ISS-may(n) nuts hai(n)?'},
  {category:'Restaurants',context:'Restaurant',english:'Everything was very good.',natural:'Sab bahut achha tha.',phonetic:'Sub buh-HUT UCH-chhaa thaa.'},

  // Shopping / UPI
  {category:'Shopping & UPI',context:'Shopkeeper',english:'How much is this?',natural:'Ye kitne ka hai?',phonetic:'Yay KIT-nay kaa hai?'},
  {category:'Shopping & UPI',context:'Shopkeeper',english:'Can you give me a better price?',natural:'Thoda better price de dijiye.',phonetic:'THOH-daa better price day DEE-jee-yay.'},
  {category:'Shopping & UPI',context:'Shopkeeper',english:'Do you have this in another size?',natural:'Ye doosre size mein hai?',phonetic:'Yay DOOS-ray size may(n) hai?'},
  {category:'Shopping & UPI',context:'Shopkeeper',english:'Do you have another color?',natural:'Koi aur color hai?',phonetic:'Koyee aur color hai?'},
  {category:'Shopping & UPI',context:'Shopkeeper',english:'Can I pay by UPI?',natural:'UPI chalega?',phonetic:'U-P-I chuh-LAY-gaa?'},
  {category:'Shopping & UPI',context:'Shopkeeper',english:'Please show me the QR code.',natural:'QR code dikha dijiye.',phonetic:'Q-R code DI-khaa DEE-jee-yay.'},
  {category:'Shopping & UPI',context:'Shopkeeper',english:'The payment went through.',natural:'Payment ho gaya.',phonetic:'Payment hoh GUH-yaa.'},
  {category:'Shopping & UPI',context:'Shopkeeper',english:'The payment did not go through.',natural:'Payment nahi hua.',phonetic:'Payment nuh-HEE(n) hoo-aa.'},
  {category:'Shopping & UPI',context:'Shopkeeper',english:'I am just looking, thank you.',natural:'Bas dekh raha hoon, thank you.',phonetic:'Bus daykh RUH-haa hoo(n), thank you.'},
  {category:'Shopping & UPI',context:'Shopkeeper',english:'Do you have change?',natural:'Change hai?',phonetic:'Change hai?'},

  // Doctor / pharmacy
  {category:'Doctor & pharmacy',context:'Doctor',english:'I have had this pain since yesterday.',natural:'Kal se yahan dard ho raha hai.',phonetic:'Kul say ya-HAAN durd hoh RUH-haa hai.'},
  {category:'Doctor & pharmacy',context:'Doctor',english:'I have a fever.',natural:'Mujhe bukhar hai.',phonetic:'MOO-jhay boo-KHAAR hai.'},
  {category:'Doctor & pharmacy',context:'Doctor',english:'I have a cough.',natural:'Mujhe khaansi hai.',phonetic:'MOO-jhay KHAA(n)-see hai.'},
  {category:'Doctor & pharmacy',context:'Doctor',english:'I feel nauseous.',natural:'Mujhe nausea ho raha hai.',phonetic:'MOO-jhay nausea hoh RUH-haa hai.'},
  {category:'Doctor & pharmacy',context:'Doctor',english:'Is this medicine safe to take with food?',natural:'Ye medicine khane ke saath le sakta hoon?',phonetic:'Yay medicine KHAA-nay kay saath lay SUK-taa hoo(n)?'},
  {category:'Doctor & pharmacy',context:'Doctor',english:'How often should I take this?',natural:'Ye kitni baar lena hai?',phonetic:'Yay KIT-nee baar LAY-naa hai?'},
  {category:'Doctor & pharmacy',context:'Doctor',english:'Should I take this before or after food?',natural:'Ye khane se pehle lena hai ya baad mein?',phonetic:'Yay KHAA-nay say PAY-lay LAY-naa hai yaa baad may(n)?'},
  {category:'Doctor & pharmacy',context:'Doctor',english:'Do I need a prescription?',natural:'Prescription chahiye?',phonetic:'Prescription CHAA-hee-yay?'},
  {category:'Doctor & pharmacy',context:'Doctor',english:'Do you have a generic version?',natural:'Iska generic version hai?',phonetic:'ISS-kaa generic version hai?'},
  {category:'Doctor & pharmacy',context:'Doctor',english:'When should I come back?',natural:'Mujhe dobara kab aana hai?',phonetic:'MOO-jhay doh-BAA-raa kub AA-naa hai?'},

  // Social / respectful
  {category:'Social & respectful',context:'Friend',english:'How have you been?',natural:'Kaise ho?',phonetic:'KAI-say hoh?'},
  {category:'Social & respectful',context:'Friend',english:'It has been a long time.',natural:'Bahut time ho gaya.',phonetic:'Buh-HUT time hoh GUH-yaa.'},
  {category:'Social & respectful',context:'Friend',english:'Your haircut looks great.',natural:'Bhai, haircut mast hai!',phonetic:'Bhai, haircut must hai!'},
  {category:'Social & respectful',context:'Friend',english:'Let us meet sometime this week.',natural:'Is week kabhi milte hain.',phonetic:'Iss week kuh-BHEE mil-tay hai(n).'},
  {category:'Social & respectful',context:'Older person',english:'How are you?',natural:'Aap kaise hain?',phonetic:'Aap KAI-say hai(n)?'},
  {category:'Social & respectful',context:'Older person',english:'Please sit down.',natural:'Aap baithiye.',phonetic:'Aap BAI-thee-yay.'},
  {category:'Social & respectful',context:'Older person',english:'Would you like some tea?',natural:'Aap chai lenge?',phonetic:'Aap chai LAY(n)-gay?'},
  {category:'Social & respectful',context:'Older person',english:'Thank you very much.',natural:'Bahut bahut shukriya.',phonetic:'Buh-HUT buh-HUT SHOOK-ree-yaa.'},
  {category:'Social & respectful',context:'Professional',english:'Could you please help me with this?',natural:'Aap ismein meri help kar sakte hain?',phonetic:'Aap ISS-may(n) MAY-ree help kur SUK-tay hai(n)?'},
  {category:'Social & respectful',context:'Professional',english:'I understand, thank you.',natural:'Samajh gaya, thank you.',phonetic:'Suh-MUJH GUH-yaa, thank you.'},

  // Travel / emergency
  {category:'Travel & emergencies',context:'Professional',english:'Where is the check-in counter?',natural:'Check-in counter kahan hai?',phonetic:'Check-in counter kuh-HAAN hai?'},
  {category:'Travel & emergencies',context:'Professional',english:'Where is the security check?',natural:'Security check kahan hai?',phonetic:'Security check kuh-HAAN hai?'},
  {category:'Travel & emergencies',context:'Professional',english:'Which gate should I go to?',natural:'Mujhe kaunse gate pe jaana hai?',phonetic:'MOO-jhay KOWN-say gate pay JAA-naa hai?'},
  {category:'Travel & emergencies',context:'Professional',english:'Is the flight delayed?',natural:'Flight delay hai kya?',phonetic:'Flight delay hai kyaa?'},
  {category:'Travel & emergencies',context:'Professional',english:'My bag has not arrived.',natural:'Mera bag nahi aaya.',phonetic:'MAY-raa bag nuh-HEE(n) AA-yaa.'},
  {category:'Travel & emergencies',context:'Professional',english:'I need help.',natural:'Mujhe help chahiye.',phonetic:'MOO-jhay help CHAA-hee-yay.'},
  {category:'Travel & emergencies',context:'Professional',english:'Please call the police.',natural:'Police ko call kijiye.',phonetic:'Police koh call KEE-jee-yay.'},
  {category:'Travel & emergencies',context:'Doctor',english:'I need a doctor.',natural:'Mujhe doctor chahiye.',phonetic:'MOO-jhay doctor CHAA-hee-yay.'},
  {category:'Travel & emergencies',context:'Professional',english:'I lost my phone.',natural:'Mera phone kho gaya.',phonetic:'MAY-raa phone khoh GUH-yaa.'},
  {category:'Travel & emergencies',context:'Professional',english:'Can you help me find this address?',natural:'Ye address dhoondhne mein help karenge?',phonetic:'Yay address DHOON-dhnay may(n) help kuh-RAY(n)-gay?'}
];