window.BOLNA_PHRASE_LIBRARY=[
{category:'Getting around',context:'Driver',english:'Please stop right here.',natural:'Bhaiya, bas yahin rok dena.',phonetic:'BHAI-yaa, bus ya-HEE(n) rohk DAY-naa'},
{category:'Getting around',context:'Driver',english:'Please go a little further.',natural:'Thoda aage chaliye.',phonetic:'THOH-daa AA-gay cha-LEE-yay'},
{category:'Getting around',context:'Driver',english:'Take the next left.',natural:'Agla left le lijiye.',phonetic:'UG-laa left lay LEE-jee-yay'},
{category:'Getting around',context:'Driver',english:'Take the next right.',natural:'Agla right le lijiye.',phonetic:'UG-laa right lay LEE-jee-yay'},
{category:'Getting around',context:'Driver',english:'Please follow Google Maps.',natural:'Google Maps follow kar lijiye.',phonetic:'Google Maps follow kur LEE-jee-yay'},
{category:'Getting around',context:'Driver',english:'Please wait here for five minutes.',natural:'Yahin paanch minute wait kar lijiye.',phonetic:'ya-HEE(n) paanch minute wait kur LEE-jee-yay'},
{category:'Getting around',context:'Driver',english:'How long will it take?',natural:'Kitna time lagega?',phonetic:'KIT-naa time laa-GAY-gaa'},
{category:'Getting around',context:'Driver',english:'Is there a lot of traffic?',natural:'Traffic zyada hai kya?',phonetic:'Traffic ZYAA-daa hai kyaa'},

{category:'Home & household',context:'Household',english:'Please come tomorrow morning.',natural:'Kal subah aa jaiye.',phonetic:'kul SOO-buh aa JAA-ee-yay'},
{category:'Home & household',context:'Household',english:'Can you come a little earlier?',natural:'Thoda jaldi aa sakte ho?',phonetic:'THOH-daa JUL-dee aa SUK-tay hoh'},
{category:'Home & household',context:'Household',english:'Please close the door.',natural:'Darwaza band kar dena.',phonetic:'dur-WAA-zaa bund kur DAY-naa'},
{category:'Home & household',context:'Household',english:'Please leave this here.',natural:'Yeh yahin rakh dena.',phonetic:'yay ya-HEE(n) rukh DAY-naa'},
{category:'Home & household',context:'Household',english:'Please clean this first.',natural:'Pehle yeh clean kar dena.',phonetic:'PAY-lay yay clean kur DAY-naa'},
{category:'Home & household',context:'Household',english:'Please turn the AC down a little.',natural:'AC thoda kam kar dena.',phonetic:'A-C THOH-daa kum kur DAY-naa'},
{category:'Home & household',context:'Household',english:'Please turn the AC up a little.',natural:'AC thoda badha dena.',phonetic:'A-C THOH-daa bu-DHAA DAY-naa'},
{category:'Home & household',context:'Household',english:'We do not need this today.',natural:'Aaj iski zaroorat nahin hai.',phonetic:'aaj ISS-kee zu-ROO-rut nuh-HEE(n) hai'},

{category:'Apartment & maintenance',context:'Household',english:'The AC is not working.',natural:'AC kaam nahin kar raha hai.',phonetic:'A-C kaam nuh-HEE(n) kur RAA-haa hai'},
{category:'Apartment & maintenance',context:'Household',english:'There is no hot water.',natural:'Garam paani nahin aa raha hai.',phonetic:'GU-rum PAA-nee nuh-HEE(n) aa RAA-haa hai'},
{category:'Apartment & maintenance',context:'Household',english:'There is a water leak here.',natural:'Yahan paani leak ho raha hai.',phonetic:'yu-HAAN PAA-nee leak hoh RAA-haa hai'},
{category:'Apartment & maintenance',context:'Household',english:'When can someone come fix it?',natural:'Koi kab aake theek kar sakta hai?',phonetic:'koy kub AA-kay theek kur SUK-taa hai'},
{category:'Apartment & maintenance',context:'Household',english:'Please call me before coming.',natural:'Aane se pehle mujhe call kar dena.',phonetic:'AA-nay say PAY-lay moo-jhay call kur DAY-naa'},
{category:'Apartment & maintenance',context:'Security',english:'Please send maintenance upstairs.',natural:'Maintenance ko upar bhej dijiye.',phonetic:'Maintenance koh OO-pur bhayj DEE-jee-yay'},
{category:'Apartment & maintenance',context:'Security',english:'Which apartment are you going to?',natural:'Aap kis flat mein ja rahe hain?',phonetic:'aap kiss flat may(n) jaa RAA-hay hai(n)'},
{category:'Apartment & maintenance',context:'Security',english:'Please let them come up.',natural:'Unko upar aane dijiye.',phonetic:'OON-koh OO-pur AA-nay DEE-jee-yay'},

{category:'Security & visitors',context:'Security',english:'I am expecting a guest.',natural:'Mera guest aane wala hai.',phonetic:'MAY-raa guest AA-nay WAA-laa hai'},
{category:'Security & visitors',context:'Security',english:'Please send them up.',natural:'Unko upar bhej dijiye.',phonetic:'OON-koh OO-pur bhayj DEE-jee-yay'},
{category:'Security & visitors',context:'Security',english:'Please call me when they arrive.',natural:'Woh aaye to mujhe call kar dena.',phonetic:'woh AA-yay toh moo-jhay call kur DAY-naa'},
{category:'Security & visitors',context:'Security',english:'The delivery person can come up.',natural:'Delivery wale ko upar bhej dijiye.',phonetic:'Delivery WAA-lay koh OO-pur bhayj DEE-jee-yay'},
{category:'Security & visitors',context:'Security',english:'Please leave the package at security.',natural:'Package security pe chhod dena.',phonetic:'Package security pay chhohd DAY-naa'},
{category:'Security & visitors',context:'Security',english:'I will come downstairs.',natural:'Main neeche aa raha hoon.',phonetic:'mai(n) NEE-chay aa RAA-haa hoo(n)'},
{category:'Security & visitors',context:'Security',english:'Which gate should I use?',natural:'Kaunsa gate use karna hai?',phonetic:'KOWN-saa gate use KUR-naa hai'},
{category:'Security & visitors',context:'Security',english:'Please open the gate.',natural:'Gate khol dijiye.',phonetic:'gate khohl DEE-jee-yay'},

{category:'Delivery',context:'Delivery',english:'Please leave it at the door.',natural:'Door pe chhod dena.',phonetic:'door pay chhohd DAY-naa'},
{category:'Delivery',context:'Delivery',english:'Please leave it at the gate.',natural:'Gate pe chhod dena.',phonetic:'gate pay chhohd DAY-naa'},
{category:'Delivery',context:'Delivery',english:'Please call me when you arrive.',natural:'Pahunch ke mujhe call kar dena.',phonetic:'pu-HOONCH kay moo-jhay call kur DAY-naa'},
{category:'Delivery',context:'Delivery',english:'I will come downstairs in two minutes.',natural:'Main do minute mein neeche aa raha hoon.',phonetic:'mai(n) doh minute may(n) NEE-chay aa RAA-haa hoo(n)'},
{category:'Delivery',context:'Delivery',english:'Please send your location on WhatsApp.',natural:'WhatsApp pe location bhej dena.',phonetic:'WhatsApp pay location bhayj DAY-naa'},
{category:'Delivery',context:'Delivery',english:'I cannot find you.',natural:'Aap dikh nahin rahe hain.',phonetic:'aap dikh nuh-HEE(n) RAA-hay hai(n)'},
{category:'Delivery',context:'Delivery',english:'I am at the main gate.',natural:'Main main gate pe hoon.',phonetic:'mai(n) main gate pay hoo(n)'},
{category:'Delivery',context:'Delivery',english:'Please wait two minutes.',natural:'Do minute wait kar lijiye.',phonetic:'doh minute wait kur LEE-jee-yay'},

{category:'Restaurants',context:'Restaurant',english:'Can I get the bill?',natural:'Bill le aaiye, please.',phonetic:'bill lay AA-ee-yay, please'},
{category:'Restaurants',context:'Restaurant',english:'Please make it a little less spicy.',natural:'Thoda kam spicy karna, please.',phonetic:'THOH-daa kum spicy KUR-naa, please'},
{category:'Restaurants',context:'Restaurant',english:'Please make it without chili.',natural:'Mirchi ke bina banana, please.',phonetic:'MIR-chee kay BI-naa bu-NAA-naa, please'},
{category:'Restaurants',context:'Restaurant',english:'Can you pack this to go?',natural:'Isko pack kar dijiye.',phonetic:'ISS-koh pack kur DEE-jee-yay'},
{category:'Restaurants',context:'Restaurant',english:'Do you have bottled water?',natural:'Bottled water hai?',phonetic:'Bottled water hai'},
{category:'Restaurants',context:'Restaurant',english:'Can we get a table for two?',natural:'Do logon ke liye table milega?',phonetic:'doh LOH-goh(n) kay LEE-yay table mi-LAY-gaa'},
{category:'Restaurants',context:'Restaurant',english:'Is this vegetarian?',natural:'Yeh veg hai?',phonetic:'yay veg hai'},
{category:'Restaurants',context:'Restaurant',english:'No onions, please.',natural:'Pyaaz mat daalna, please.',phonetic:'pyaaz mut DAAL-naa, please'},

{category:'Shopping & payments',context:'Shopkeeper',english:'How much is this?',natural:'Yeh kitne ka hai?',phonetic:'yay KIT-nay kaa hai'},
{category:'Shopping & payments',context:'Shopkeeper',english:'Do you have another size?',natural:'Dusra size hai?',phonetic:'DOOS-raa size hai'},
{category:'Shopping & payments',context:'Shopkeeper',english:'Do you have a smaller size?',natural:'Chhota size hai?',phonetic:'CHHOH-taa size hai'},
{category:'Shopping & payments',context:'Shopkeeper',english:'Do you have a bigger size?',natural:'Bada size hai?',phonetic:'BU-daa size hai'},
{category:'Shopping & payments',context:'Shopkeeper',english:'Can I pay by UPI?',natural:'UPI chalega?',phonetic:'U-P-I chu-LAY-gaa'},
{category:'Shopping & payments',context:'Shopkeeper',english:'Do you take cards?',natural:'Card chalega?',phonetic:'card chu-LAY-gaa'},
{category:'Shopping & payments',context:'Shopkeeper',english:'Can you give me a better price?',natural:'Thoda better price de sakte ho?',phonetic:'THOH-daa better price day SUK-tay hoh'},
{category:'Shopping & payments',context:'Shopkeeper',english:'I am just looking.',natural:'Bas dekh raha hoon.',phonetic:'bus daykh RAA-haa hoo(n)'},

{category:'Doctor & pharmacy',context:'Doctor',english:'I have had this pain since yesterday.',natural:'Kal se yeh pain ho raha hai.',phonetic:'kul say yay pain hoh RAA-haa hai'},
{category:'Doctor & pharmacy',context:'Doctor',english:'How often should I take this?',natural:'Yeh kitni baar lena hai?',phonetic:'yay KIT-nee baar LAY-naa hai'},
{category:'Doctor & pharmacy',context:'Doctor',english:'Should I take this with food?',natural:'Yeh khane ke saath lena hai?',phonetic:'yay KHAA-nay kay saath LAY-naa hai'},
{category:'Doctor & pharmacy',context:'Doctor',english:'Do I need to come back?',natural:'Mujhe wapas aana hai?',phonetic:'moo-jhay WAA-pus AA-naa hai'},
{category:'Doctor & pharmacy',context:'Doctor',english:'Can you explain that one more time?',natural:'Ek baar aur samjha dijiye.',phonetic:'ayk baar ohr sum-JHAA DEE-jee-yay'},
{category:'Doctor & pharmacy',context:'Doctor',english:'Is this medicine available here?',natural:'Yeh medicine yahan milegi?',phonetic:'yay medicine yu-HAAN mi-LAY-gee'},
{category:'Doctor & pharmacy',context:'Doctor',english:'Do you have the generic version?',natural:'Iska generic version hai?',phonetic:'ISS-kaa generic version hai'},
{category:'Doctor & pharmacy',context:'Doctor',english:'Is there a pharmacy nearby?',natural:'Paas mein pharmacy hai?',phonetic:'paas may(n) pharmacy hai'},

{category:'Friends & everyday',context:'Friend',english:'What are you doing?',natural:'Kya kar rahe ho?',phonetic:'kyaa kur RAA-hay hoh'},
{category:'Friends & everyday',context:'Friend',english:'Where are you?',natural:'Kahan ho?',phonetic:'ku-HAAN hoh'},
{category:'Friends & everyday',context:'Friend',english:'I am on my way.',natural:'Main aa raha hoon.',phonetic:'mai(n) aa RAA-haa hoo(n)'},
{category:'Friends & everyday',context:'Friend',english:'I will be there in ten minutes.',natural:'Main das minute mein pahunch raha hoon.',phonetic:'mai(n) dus minute may(n) pu-HOONCH RAA-haa hoo(n)'},
{category:'Friends & everyday',context:'Friend',english:'Let us go.',natural:'Chalo chalte hain.',phonetic:'chu-LOH CHUL-tay hai(n)'},
{category:'Friends & everyday',context:'Friend',english:'That was really good.',natural:'Woh bahut achha tha.',phonetic:'woh bu-HUT UCH-chhaa thaa'},
{category:'Friends & everyday',context:'Friend',english:'Your haircut looks great.',natural:'Bhai, haircut mast hai!',phonetic:'bhai, HAIR-cut must hai'},
{category:'Friends & everyday',context:'Friend',english:'See you tomorrow.',natural:'Kal milte hain.',phonetic:'kul MIL-tay hai(n)'}
];
